apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rule
  namespace: sock-shop
spec:
  ingressClassName: nginx
  rules:
  - host: capstone.papsoccer.com.ng
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
